Add database
FORESSS/java-filmorate pull request #7
Opened 2024-06-26 10:02 UTC by FORESSS

2024-06-26 17:48 UTC, EugeneLenkevich requested changes
Привет, Сергей! Спасибо за PR.

В целом все верно, работа выглядит более чем солидно. Есть моменты по оптимизации запросов и еще больше архитектурный вопрос по распределению обязанностей между слоями, оставил комментарии, посмотри, пожалуйста :)

2024-06-26 17:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDBRepository.java
> +            Set<Integer> genresId = genreRepository.getGenresByFilm(filmId);
Насколько понимаю мы тут в цикле по всем фильмам делаем N запросов к БД. 
Вообще, обращение к БД достаточно дорогая операция потому их количество стоит минимизировать, получится ли переделать это так, чтобы все необходимые данные можно было вытащить за один запрос? :)

Как минимум в самом просто м случае можно сделать select * from <таблица> where id in (:ids)
где ids - массив идентификаторов

2024-06-26 17:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDBRepository.java
> +        return !sameFilmList.isEmpty();
Можно попроще запрос такой сделать, без выборки данных :)

https://stackoverflow.com/questions/7471625/fastest-check-if-row-exists-in-postgresql

2024-06-26 17:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDBRepository.java
> +        var likes = Optional.ofNullable(jdbc.queryForObject(FilmTextRequests.GET_USERLIKE_TO_FILM, Integer.class, filmId, userId));
Тут Optional наверно особо и не нужен... без него бы код был чутка попроще и покороче
Когда он нужен - когда мы из метода возвращаем значение, так мы упрощаем внешнему коду обработку результатов.
Давай попробуем без него сделать, будет ли проще

2024-06-26 17:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDBRepository.java
> +            Set<Integer> genresId = genreRepository.getGenresByFilm(filmId);
Опять таки, запросы в цикле, не особо это эффективно, заменить бы одним запросом :)

2024-06-26 17:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/repository/friends/FriendsDBRepository.java
> +        if (result.isEmpty()) {
result.get()

От Optional лучше сразу избавиться, как минимум
Friends result = optional.orElse(...);


https://struchkov.dev/blog/ru/optional-in-java/

2024-06-26 17:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/repository/friends/FriendsDBRepository.java
> +        var applicantToApprovingStatus = getFriendshipStatus(applicantId, approvingId);
А тут похоже кстати что логика метода относится к бизнес-слою, то есть ее лучше перенести в сервис, на уровне репозиториев мы работаем с выборкой данных, в сервисах с логикой предметной области, это проще всего проверить по глаголам, глаголами какой области мы оперируем в методе - проверяем статусами дружбы  :)

По классике обязанности распределяются вот так

> Первый слой абстракции — это слой доступа к данным. В задачи данного слоя входит абстрагирование от базы данных. SQL-запросы к базе данных, в которой и хранятся данные приложения, скрываются за фасадом, который использует бизнес-слой.
> 
> Второй слой абстракции — это слой бизнес-логики. Он содержит объекты предметной области, а также функции для работы с ними. Эти функции и реализуют данную бизнес-логику.
> 
> Третий слой абстракции — это слой взаимодействия с пользователем. Данный слой включает компоненты пользовательского интерфейса.

2024-06-26 19:19 UTC, FORESSS commented on src/main/java/ru/yandex/practicum/filmorate/repository/friends/FriendsDBRepository.java
> +        var applicantToApprovingStatus = getFriendshipStatus(applicantId, approvingId);
У меня нет контроллера и сервиса для модели Friends, поэтому этот метод только здесь можно оставить...

2024-06-26 19:29 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/repository/friends/FriendsDBRepository.java
> +        var applicantToApprovingStatus = getFriendshipStatus(applicantId, approvingId);
Ну ок, пусть так остается

2024-06-26 19:42 UTC, FORESSS commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDBRepository.java
> +            Set<Integer> genresId = genreRepository.getGenresByFilm(filmId);
Всё! Сдаюсь! При одном запросе к БД тесты не проходят!

2024-06-26 21:06 UTC, FORESSS commented
Ну вот и всё!((( не успел!(((

2024-06-26 21:07 UTC, FORESSS commented
Ну вот и всё!((( не успел!((( досадно!

2024-06-27 03:39 UTC, EugeneLenkevich approved these changes
Спасибо
Ну, в целом, основной смысл вроде понят. Не будем особо зарываться, в таком виде запросы муторно писать, да и так, вручную, сейчас их особо и не пишут, дальше будет JPA, там это все проще :)

2024-06-27 03:39 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDBRepository.java
> +        return exists != null && exists;
От проверки на null кстати можно вот так избавится
return Boolean.TRUE.equals(exists)

2024-06-27 04:50 UTC, merged